import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DM_Sans } from "next/font/google";
import favicon from "@/assets/favicon.png";

const dmSans = DM_Sans({
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Gerbang Suara - #DemokrasiTanpaKeraguan",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* Add Favicon manually */}
            <head>
                <link
                    rel="shortcut icon"
                    href="@/app/favicon.png"
                    type="image/x-icon"
                />
            </head>
            <body className={dmSans.className}>{children}</body>
        </html>
    );
}
